# -*- coding: utf-8 -*-
"""ProjOO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJB9mVMCREUIvARLRgP8x-T-8Gr0xzYm
"""

from abc import ABC, abstractmethod

class Notification(ABC):
    @abstractmethod
    def println(self, message):
        pass


class emailNotification(Notification):
    def println(self, message):
        print(f"Email: {message}")


class SMSNotification(Notification):
    def println(self, message):
        print(f"SMS: {message}")


class PushNotification(Notification):
    def println(self, message):
        print(f"Push notification: {message}")


class NotificationFactory():
    @staticmethod
    def createNotification(type):
        if type == "email":
            return emailNotification()
        elif type == "SMS":
            return SMSNotification()
        elif type == "push":
            return PushNotification()
        else:
            print("Error, wrong notification method")


class Configuration:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance= super().__new__(cls)
            cls._instance.name = "Global Configuration for exercise"
            cls._instance.max_retrys = 5
        return cls._instance


class ProxyNotification(Notification):
    def __init__(self, real_notificator):
      self.real_notificator = real_notificator
      self.retrys = 0
      self.config = Configuration()

    def println(self, message):
      print(f"[LOG] Proxy trying to send message: {message}")

      if self.retrys < self.config.max_retrys:
        try:
          self.real_notificator.println(message)
          print("[LOG] Message sent with sucess")
        except:
          self.retrys += 1
          print("[LOG] Failed to sent message")
          print(f"[LOG] Tried {self.retrys}")
      else:
        print("[LOG] Max retries to send message achived, no more messages")


class Adaptator (ABC):
    @abstractmethod
    def send(self, message, channel):
        pass


class AdaptatorNotificationFactory(Adaptator):
    def __init__(self, channel):
      self.channel = channel

    def send(self, message):
      factory = NotificationFactory()
      real_notificator = factory.createNotification(self.channel)
      proxy = ProxyNotification(real_notificator)
      proxy.println(message)


factory = AdaptatorNotificationFactory("email")
factory.send("Bom dia, boa tarde e boa noite caro professor, espero que você esteja com bom humor e me de nota 10 nessa atividade")