# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJB9mVMCREUIvARLRgP8x-T-8Gr0xzYm
"""

from abc import ABC, abstractmethod

class Notification(ABC):
    @abstractmethod
    def println(self, message):
        pass


class emailNotification(Notification):
    def println(self, message):
        print(f"Email: {message}")


class SMSNotification(Notification):
    def println(self, message):
        print(f"SMS: {message}")


class PushNotification(Notification):
    def println(self, message):
        print(f"Push notification: {message}")

class NotificationFactory():
    @staticmethod
    def createNotification(type):
        if type == "email":
            return emailNotification()
        elif type == "SMS":
            return SMSNotification()
        elif type == "push":
            return PushNotification()
        else:
            print("Error, wrong notification method")


class Configuration:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance= super().__new__(cls)
            cls._instance.name = "Global Configuration for exercise"
            cls._instance.max_retrys = 5
        return cls._instance


factory = NotificationFactory()

notificator = factory.createNotification("email")
notificator.println("Bom dia, boa tarde e boa noite caro professor, espero que você esteja com bom humor e me de nota 10 nessa atividade")